name: Build, Test, and Deploy Python App to Azure Web App - book-tracker-mihajlo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # --------------------------
  # 🧪 TEST JOB
  # --------------------------
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: pytest -q

  # --------------------------
  # 🚀 DEPLOY JOB
  # --------------------------
  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_53CF8E689028439E88B3497C097DB9B7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1101E28D32214FB7B506CFFBCBF57529 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AE049BBC9C1945DF9CA5F4C92FBD26AF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'book-tracker-mihajlo'
          slot-name: 'Production'
